"use client"

import { Filter, Search, SlidersHorizontal, X } from "lucide-react"
import { useEffect, useMemo, useState } from "react"
import { ProductCard } from "@/components/product-card"
import { SiteHeader } from "@/components/site-header"
import type { Product } from "@/lib/data"

const vehicleTypes = ["All types", "Sedan", "SUV", "Coupe", "Supercar", "Sports car", "Motorcycle", "Truck"]
export default function StorePage() {
  const [products, setProducts] = useState<Product[]>([]); const [search, setSearch] = useState(""); const [brand, setBrand] = useState("All brands"); const [type, setType] = useState("All types"); const [sort, setSort] = useState("newest"); const [filters, setFilters] = useState(false)
  useEffect(() => { fetch("/api/products").then(r => r.json()).then(d => setProducts(d.products ?? [])).catch(() => setProducts([])) }, [])
  const brands = useMemo(() => ["All brands", ...Array.from(new Set(products.map(product => product.brand))).sort()], [products])
  const shown = useMemo(() => products.filter(product => (brand === "All brands" || product.brand === brand) && (type === "All types" || product.vehicle_type === type) && `${product.name} ${product.brand} ${product.vehicle_type}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => sort === "price-low" ? (a.price_usd ?? Infinity) - (b.price_usd ?? Infinity) : sort === "price-high" ? (b.price_usd ?? 0) - (a.price_usd ?? 0) : 0), [products, brand, type, search, sort])
  const clear = () => { setSearch(""); setBrand("All brands"); setType("All types"); setSort("newest") }
  return <main className="storefront"><SiteHeader active="shop" /><section className="shop-intro"><p className="eyebrow">THE RYVN COLLECTION</p><h1>Find the right<br /><em>starting point.</em></h1><p>Browse production-ready automotive assets for your Roblox experience. Every listing is published from the live RYVN catalog.</p></section><section className="shop-layout"><aside className={filters ? "filter-panel is-open" : "filter-panel"} aria-label="Product filters"><div className="filter-head"><strong>Refine collection</strong><button onClick={() => setFilters(false)} aria-label="Close filters"><X size={18} /></button></div><label>Search <span className="search-input"><Search size={16} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search models" /></span></label><label>Brand<select value={brand} onChange={e => setBrand(e.target.value)}>{brands.map(value => <option key={value}>{value}</option>)}</select></label><label>Vehicle type<select value={type} onChange={e => setType(e.target.value)}>{vehicleTypes.map(value => <option key={value}>{value}</option>)}</select></label><button className="filter-clear" onClick={clear}>Clear filters</button></aside><div className="shop-results"><div className="result-toolbar"><p><span>{shown.length}</span> model{shown.length === 1 ? "" : "s"} available</p><button className="mobile-filter" onClick={() => setFilters(true)}><Filter size={16} /> Filter</button><label>Sort by <select value={sort} onChange={e => setSort(e.target.value)}><option value="newest">Newest</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></label></div><div className="product-grid store-grid">{shown.map((product, index) => <ProductCard key={product.id} product={product} priority={index < 2} />)}</div>{!shown.length && <div className="empty-state"><SlidersHorizontal size={22} /><h2>No models match those filters.</h2><p>Try a different vehicle type, brand, or search term.</p><button className="button button-ghost" onClick={clear}>Reset filters</button></div>}</div></section></main>
}
