"use client"
import Link from "next/link"
import Image from "next/image"
import { useEffect, useState } from "react"
import { ArrowRight } from "lucide-react"
import { brands } from "@/lib/catalog"
import type { Product } from "@/lib/data"
type User={username:string}
export default function StorePage(){const [products,setProducts]=useState<Product[]>([]),[brand,setBrand]=useState("All vehicles"),[user,setUser]=useState<User|null>(null);useEffect(()=>{fetch("/api/products").then(r=>r.json()).then(d=>setProducts(d.products??[]));fetch("/api/session").then(r=>r.json()).then(d=>setUser(d.user??null))},[]);const shown=brand==="All vehicles"?products:products.filter(p=>p.brand===brand);return <main><header className="site-header"><Link href="/" className="wordmark">RYVN<span>®</span></Link><nav className="nav" aria-label="Main navigation"><Link href="/store">Store</Link><Link href="/commissions">Commissions</Link><Link href="/accessibility">Accessibility</Link></nav><div className="header-actions"><Link className="quiet-link" href="/profile">{user?user.username:"Profile"}</Link>{user?:<Link className="button button-small" href="/login">Sign in with Discord</Link>}</div></header><section className="catalog" aria-labelledby="catalog-title"><div className="catalog-heading"><div><p className="eyebrow">RYVN STORE</p><h1 id="catalog-title">Find your next build.</h1></div><p>Browse published vehicles by marque. The collection scrolls independently as the store grows.</p></div><div className="catalog-layout"><aside className="brand-rail" aria-label="Vehicle brands"><p className="rail-label">BRANDS</p>{brands.map(item=><button key={item} onClick={()=>setBrand(item)} className={brand===item?"brand active":"brand"}>{item}</button>)}<Link className="commission-prompt" href="/commissions"><span>Need something specific?</span> Commission a vehicle <ArrowRight size={15}/></Link></aside><div className="product-scroll" aria-live="polite">{shown.map((product,index)=><article className="product-card" key={product.slug}><div className="vehicle-art">{product.hero_image_url?<Image src={product.hero_image_url} alt={product.name} fill sizes="(max-width:760px) 90vw, 40vw" className="object-cover"/>:<><span className="art-number">{String(index+1).padStart(2,"0")}</span><div className="car-silhouette"/></>}<span>{product.preview_label??"PREVIEW"}</span></div><div className="product-info"><div><p>{product.brand}</p><h3>{product.name}</h3></div><span className="format">{product.vehicle_type}</span></div><div className="product-footer"><span>{product.price_robux?`${product.price_robux.toLocaleString()} R$`:product.price_usd?`$${product.price_usd}`:"Price on request"}</span><Link href={`/products/${product.slug}`}>View vehicle <ArrowRight size={16}/></Link></div></article>)}{shown.length===0&&<p className="empty-catalog">No published releases for this selection yet.</p>}</div></div></section></main>}

