"use client"
import Link from "next/link"
import { Suspense, useEffect, useState } from "react"
import { useSearchParams } from "next/navigation"
import { ArrowRight } from "lucide-react"
import type { Product } from "@/lib/data"
export default function CommissionsPage() {
  return <Suspense fallback={<main className="form-page"><header className="site-header"><Link href="/" className="wordmark">RYVN<span>®</span></Link></header><section className="form-intro"><p className="eyebrow">RYVN COMMISSIONS</p><h1>Loading commission request…</h1></section></main>}><CommissionForm /></Suspense>
}
function CommissionForm() {
  const searchParams = useSearchParams(); const selected = searchParams.get("vehicle") ?? ""
  const [products, setProducts] = useState<Product[]>([]), [status, setStatus] = useState("")
  useEffect(() => { fetch("/api/products").then(r => r.json()).then(data => setProducts(data.products ?? [])).catch(() => setStatus("The live catalog could not be loaded.")) }, [])
  async function submit(form: HTMLFormElement) { const data = new FormData(form); setStatus("Submitting request…"); const response = await fetch("/api/commissions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ vehicle: data.get("vehicle"), requestTypes: data.getAll("requestType"), details: data.get("details"), attachmentUrl: data.get("attachmentUrl") }) }); const result = await response.json(); setStatus(response.ok ? (result.ticketCreated ? "Request saved and a private Discord ticket was created." : "Request saved. A staff member will follow up.") : result.error ?? "Unable to save this request.") }
  return <main className="form-page"><header className="site-header"><Link href="/" className="wordmark">RYVN<span>®</span></Link><Link className="quiet-link" href="/store">Catalog</Link></header><section className="form-intro"><p className="eyebrow">RYVN COMMISSIONS</p><h1>Shape the details.</h1><p>Request an edit for a catalog vehicle. Your request becomes a tracked job and opens a private Discord ticket when the support bot is configured.</p></section><form className="commission-form" onSubmit={e => { e.preventDefault(); submit(e.currentTarget) }}><label>Vehicle<select name="vehicle" defaultValue={selected}><option value="">Choose a vehicle</option>{products.map(p=><option key={p.slug} value={p.slug}>{p.brand} {p.name}</option>)}</select></label><fieldset><legend>What would you like changed?</legend><label className="check-row"><input name="requestType" value="Remove badge / emblems and model divot" type="checkbox"/> Remove badge / emblems and the model divot</label><label className="check-row"><input name="requestType" value="Custom emblem or vehicle name" type="checkbox"/> Add a custom emblem or vehicle name</label><label className="check-row"><input name="requestType" value="Other visual edit" type="checkbox"/> Other visual edit</label></fieldset><label>Describe the request<textarea name="details" required minLength={10} maxLength={4000} placeholder="Tell us what needs to change, where it is on the vehicle, and how you want it to look." rows={6}/></label><label>Badge / emblem image URL <span className="optional">PNG or JPG link</span><input name="attachmentUrl" type="url" placeholder="https://…/badge.png" /><small>Paste a hosted PNG or JPG link so it is stored with the ticket and commission.</small></label><div className="ticket-note"><strong>Discord ticket</strong><p>Submitting creates a tracked commission and a private Discord ticket when the RYVN bot is configured.</p></div><button type="submit" className="button">Save commission request <ArrowRight size={16}/></button>{status && <p aria-live="polite">{status}</p>}</form></main>
}
