"use client"

import Link from "next/link"
import { ArrowRight, Boxes, Gauge, ShieldCheck, Sparkles } from "lucide-react"
import { useEffect, useState } from "react"
import { ProductCard } from "@/components/product-card"
import { SiteHeader } from "@/components/site-header"
import type { Product } from "@/lib/data"

export default function Home() {
  const [products, setProducts] = useState<Product[]>([])
  useEffect(() => { fetch("/api/products").then(r => r.json()).then(d => setProducts(d.products ?? [])).catch(() => undefined) }, [])
  return <main className="storefront"><a className="skip-link" href="#content">Skip to content</a><SiteHeader active="home" />
    <section id="content" className="premium-hero"><div className="hero-copy-wrap"><p className="eyebrow">PREMIUM ROBLOX VEHICLES</p><h1>Assets made<br />for <em>motion.</em></h1><p className="hero-lede">Purpose-built automotive models with clean geometry, detailed interiors, and ready-to-integrate delivery files for ambitious Roblox worlds.</p><div className="hero-cta"><Link className="button" href="/store">Browse models <ArrowRight size={17} /></Link><Link className="text-action" href="/commissions">Commission a custom build <ArrowRight size={15} /></Link></div><dl className="hero-metrics"><div><dt>01</dt><dd>Curated<br />releases</dd></div><div><dt>360°</dt><dd>Interactive<br />previews</dd></div><div><dt>24/7</dt><dd>Discord<br />support</dd></div></dl></div><div className="hero-vehicle" aria-label="Featured BMW vehicle preview"><div className="hero-grid" /><img src="/showcase/ryvn-bmw-showcase.jpg" alt="Purple BMW coupe at a night time service station" /><div className="hero-badge"><span>01 / FEATURED</span><strong>BMW M4</strong><small>Studio-quality vehicle asset</small></div></div></section>
    <section className="feature-rail" aria-label="RYVN benefits"><span><ShieldCheck size={17} /> Clear licensed delivery</span><span><Gauge size={17} /> Optimized for Roblox</span><span><Boxes size={17} /> Detailed, grouped files</span><span><Sparkles size={17} /> Personal support</span></section>
    <section className="featured-section"><div className="section-heading"><div><p className="eyebrow">SELECTED RELEASES</p><h2>Built to hold up<br />close.</h2></div><p>Browse the latest production-ready vehicles, inspect each asset from every angle, and find the right starting point for your next experience.</p><Link className="text-action" href="/store">View all models <ArrowRight size={15} /></Link></div><div className="product-grid">{products.slice(0, 3).map((product, index) => <ProductCard key={product.id} product={product} priority={index === 0} />)}{!products.length && <div className="empty-state"><p className="eyebrow">COLLECTION IN PROGRESS</p><h3>New releases are being prepared.</h3><p>Check back soon or start a commission for a specific vehicle.</p><Link className="button button-ghost" href="/commissions">Start a commission</Link></div>}</div></section>
    <section className="quality-section"><div><p className="eyebrow">THE RYVN STANDARD</p><h2>Every asset is made to be used, not just displayed.</h2></div><div className="quality-list"><article><span>01</span><h3>Clean delivery</h3><p>Organized files and clear product details make hand-off straightforward.</p></article><article><span>02</span><h3>Inspect before purchase</h3><p>Use media galleries and touch-friendly vehicle previews before committing.</p></article><article><span>03</span><h3>Custom-ready</h3><p>Need a different finish or detail? Continue with a tracked Discord commission.</p></article></div></section>
    <section className="commission-callout"><p className="eyebrow">MAKE IT YOURS</p><h2>Start with a vehicle.<br /><em>Finish with your vision.</em></h2><Link className="button" href="/commissions">Talk to RYVN <ArrowRight size={17} /></Link></section><footer className="store-footer"><Link href="/" className="brand-mark">RYVN<sup>®</sup></Link><p>Premium automotive assets for worlds in motion.</p><nav><Link href="/store">Shop</Link><Link href="/commissions">Commissions</Link><Link href="/accessibility">Accessibility</Link><Link href="/profile">Account</Link></nav><small>© 2026 RYVN. All rights reserved.</small></footer></main>
}
