import Link from "next/link"
import { cookies } from "next/headers"
import { ArrowRight, BadgeCheck, BookOpen, LayoutDashboard, Settings, Ticket } from "lucide-react"
import { SiteHeader } from "@/components/site-header"
import { readSession } from "@/lib/auth"
import { userById } from "@/lib/data"

export default async function ProfilePage() {
  const session = readSession((await cookies()).get("ryvn_discord_user")?.value); const account = session ? await userById(session.id) : null; const staff = account && ["owner", "editor"].includes(account.role)
  if (!session) return <main className="storefront"><SiteHeader /><section className="not-found"><p className="eyebrow">RYVN MEMBER ACCESS</p><h1>Your history belongs in one place.</h1><p className="account-lede">Connect Discord to keep private commissions, delivery information, support tickets, and reviews connected to you.</p><Link className="button" href="/login">Sign in with Discord <ArrowRight size={17} /></Link></section></main>
  return <main className="storefront"><SiteHeader /><section className="account-hero"><div className="account-avatar-large">{session.avatarUrl ? <img src={session.avatarUrl} alt="" /> : session.username.slice(0, 1).toUpperCase()}</div><div><p className="eyebrow">DISCORD MEMBER · {account?.role ?? "customer"}</p><h1>{session.username}</h1><p>Your RYVN workspace keeps your purchases, product deliveries, commissions, and Discord support history in one account.</p></div><div className="account-actions"><Link className="button" href="/commissions">New commission <ArrowRight size={16} /></Link>{staff && <Link className="button button-ghost" href="/dashboard"><LayoutDashboard size={16} /> Dashboard</Link>}</div></section><section className="account-overview"><article><BadgeCheck size={20} /><p className="eyebrow">ACCOUNT STATUS</p><h2>Connected</h2><p>Your Discord identity is securely connected to RYVN.</p><Link href="/settings">Account settings <ArrowRight size={14} /></Link></article><article><Ticket size={20} /><p className="eyebrow">COMMISSIONS</p><h2>Request a build</h2><p>Start a tracked request and continue it through private Discord support.</p><Link href="/commissions">Open commission form <ArrowRight size={14} /></Link></article><article><BookOpen size={20} /><p className="eyebrow">COLLECTION</p><h2>Explore releases</h2><p>Return to the live catalog for models, specifications, and delivery details.</p><Link href="/store">Browse shop <ArrowRight size={14} /></Link></article></section></main>
}
