import Link from "next/link"
import { notFound } from "next/navigation"
import { ArrowLeft, ArrowRight, Check, MessageSquare, Play } from "lucide-react"
import { approvedReviews, productBySlug } from "@/lib/data"

export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const product = await productBySlug((await params).slug); if (!product) notFound()
  const reviews = await approvedReviews(product.id)
  const price = product.price_robux ? `${product.price_robux.toLocaleString()} Robux` : product.price_usd ? `$${product.price_usd.toFixed(2)}` : "Pricing on request"
  return <main className="detail-page"><header className="site-header"><Link href="/" className="wordmark">RYVN<span>®</span></Link><Link className="quiet-link" href="/#catalog">Back to catalog</Link></header>
    <section className="detail-hero"><Link className="back" href="/#catalog"><ArrowLeft size={16}/> Catalog</Link><p className="eyebrow">{product.brand} / {product.vehicle_type}</p><h1>{product.name}</h1><p>{product.description}</p><div className="detail-actions"><a className="button" href="#checkout">Choose payment <ArrowRight size={16}/></a><Link className="button button-ghost" href={"/commissions?vehicle=" + product.slug}>Commission this vehicle</Link></div></section>
    <section className="media-zone"><div className="turntable">{product.hero_image_url ? <img src={product.hero_image_url} alt={`${product.name} preview`} /> : <div className="car-silhouette"/>}<span>360°</span><p>Interactive vehicle preview</p><small>{product.model_url ? "Model preview is ready to connect." : "Connect a GLB/GLTF model to enable orbit, zoom, lighting and paint previews."}</small></div><div className="media-stack"><article><Play size={20}/><p className="eyebrow">WALKAROUND</p><h2>YouTube preview</h2><span>{product.youtube_url ? "Walkaround video linked for this release." : "No walkaround has been added yet."}</span></article><article><p className="eyebrow">REFERENCE SET</p><h2>Image collage</h2><span>{product.collage_urls.length ? `${product.collage_urls.length} reference image${product.collage_urls.length === 1 ? "" : "s"} available.` : "No additional reference images have been added yet."}</span></article></div></section>
    <section className="detail-grid"><div><p className="eyebrow">INCLUDED</p><h2>Prepared for your game.</h2>{product.features.map(feature => <p className="feature" key={feature}><Check size={16}/>{feature}</p>)}</div><div id="checkout" className="checkout-card"><p className="eyebrow">PURCHASE OPTIONS</p><h3>{price}</h3><p>Choose Robux or USD at checkout. Payment providers are selected per listing by RYVN.</p><button className="button" disabled>Checkout setup in progress</button><small>Payment is intentionally unavailable until a seller account is connected.</small></div></section>
    <section className="reviews"><div><p className="eyebrow">COMMUNITY NOTES</p><h2>Reviews</h2><p>Reviews show an approved profile image and a redacted username to protect buyer privacy.</p></div><div className="review-list">{reviews.length ? reviews.map(review => <article key={review.id}><div className="avatar">{review.username.slice(0,1).toUpperCase()}</div><div><strong>{review.username.slice(0, 2)}•••</strong><span>{"★".repeat(review.rating)}{"☆".repeat(5 - review.rating)}</span><p>{review.body}</p></div></article>) : <p>No approved reviews yet.</p>}<button className="review-button"><MessageSquare size={16}/> Sign in to leave a review</button></div></section>
  </main>
}
